---

- name: "Installing and Start the Apache Web Service"
  hosts: localhost

  tasks:
  - name: "Installing Apache web Server"
    apt:
      name: apache2
      state: present
  - name: "Start The Web Server"
    service:
      name: apache2
      state: started
      enabled: true

