---
# tasks file for apache2_setup
#
#
- name: "Inatslling Apache2"
  apt:
    name: "{{ apache2_package_name }}"
    state: present

- name: "Place Custom HTML File"
  copy:
    src: index.html
    dest: "{{ html_file_path }}"

- name: "Start The Service"
  service:
    name: "{{ apache2_package_name }}"
    state: started
    enabled: yes

